Repository TeamWDTT/spaceBongBong, pull requests merged in 2023-12, with the labels that each got.

#2 Feat/#1 oop design
  airplane.png
  bullet.png
  main.py
Labels: feat

#6 Feat/#5 axis convert
  airplane.py
  bullet.py
  game.py
  main.py
Labels: feat

#15 feat: apply design
  PressStart2P.ttf
  airplane.png
  bullet.png
  bullet.py
  game.py
  heart.png
  heart.py
  images/airplane1.png
  images/airplane2.png
  images/background.png
  images/bullet1.png
  images/bullet2.png
  images/heart1.png
  images/start.png
  images/winPlayer1.png
  images/winPlayer2.png
  item.py
  item_bullet.png
  item_highres.png
  item_speed.png
Labels: feat, chore

#16 fix: added has_rotated_recently logic and modified wall coords
  airplane.py
Labels: fix

#18 chore: turn to red after crash
  airplane.py
  bullet.py
  entity.py
  game.py
  heart.py
Labels: chore
